public enum BirdsType {
    EAGLES, EMUS,MOAS, HORNEDO_PUFFIN, HAWKS, OSPREY, KIWIS, AFRICAN_JACANA, GREAT_AUK, DUKS, SWANS, GEESE, OWLS,
    ROSE_RING_PARAKEET, GRAY_PARROT,PIGEONS,SULFUR_CRESTED_COCKATOO,OTHER
}


